### ISSUE TITLE
CSS spec compliance: `!IMPORTANT` is valid – should be case insensitive

### ISSUE THREAD

**Issue by lydell** [shellscape/postcss-less#89]
* Node Version: 8.3.0
* NPM Version: 5.3.0
* postcss-less Version: 1.1.0

### LESS

```less
a{k: v !IMPORTANT;}
```

### JavaScript

```js
console.dir(require("postcss-less").parse('a{k: v !IMPORTANT;}'), {colors: true, depth: null})
```

### Expected Behavior

The declaration should be parsed as:

```
Declaration {
  prop: 'k',
  important: true,
  value: 'v'
}
```

Just like for `a{k: v !important;}`.

### Actual Behavior

The declaration is parsed as:

```
Declaration {
  prop: 'k',
  value: 'v !IMPORTANT' }
}
```

### How can we reproduce the behavior?

```js
console.dir(require("postcss-less").parse('a{k: v !IMPORTANT;}'), {colors: true, depth: null})
```

### Related

https://github.com/postcss/postcss/issues/1065

**Comment by shellscape** [comment]
Fix should go [here](https://github.com/shellscape/postcss-less/blob/master/lib/less-parser.js#L117), should be a simple regex instead of straight string compare.

**Comment by orottier** [comment]
I've fixed this for less mixins, but I think the issue should be migrated to shellscape/postcss

**Comment by shellscape** [comment]
@lydell @orottier has this one been resolved by #91?

**Comment by lydell** [comment]
@shellscape I asked myself the same question when I saw #91 and tried it – but, no, this is still an issue.
